### ISSUE TITLE
Wont run on Windows OS with FIPS enabled

### ISSUE THREAD

**Issue by veevelder** [EricZimmerman/AmcacheParser#5]
Just simply running AmcacheParser.exe on a Windows OS that has FIPS enabled causes it to crash. 
```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'LibZ.Injected.AsmZResolver' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at LibZ.Injected.AsmZResolver.Hash(String text)
   at LibZ.Injected.AsmZResolver..cctor()
   --- End of inner exception stack trace ---
   at LibZ.Injected.AsmZResolver.Initialize()
   at LibZ.Injected.LibZInitializer.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
```

This can be solved by using a different hashing algorithm instead of MD5, use SHA1 or SHA256 for example.

**Comment by EricZimmerman** [comment]
i do not use MD5 at all in AmcacheParser code. I do use libz to pack everything in a single exe, and based on the error (LibZ.Injected.AsmZResolver) thats where the issue is.

you can post an issue here:

https://github.com/MiloszKrajewski/LibZ

to see if he will fix it i suppose

**Comment by danzek** [comment]
Yep, it's an issue with security settings in Windows OS not liking that lib's call.

Full related stack trace where we see this duplicated:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for 'LibZ.Injected.AsmZResolver' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at LibZ.Injected.AsmZResolver.Hash(String text)
   at LibZ.Injected.AsmZResolver..cctor()
   --- End of inner exception stack trace ---
   at LibZ.Injected.AsmZResolver.Initialize()
   at LibZ.Injected.LibZInitializer.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
```

**Comment by EricZimmerman** [comment]
This is fixed in v1.1.0.0, to be released in the next few days. i updated ALL my software to NOT use libz anymore, so this will go away once i push those updates out.

**Comment by AbdirahmanJibril** [comment]
Just downloaded AmcacheParser from the git repo but when run it just disappears. I am running the application in  a VM. please help with this issue

**Comment by EricZimmerman** [comment]
Why would you post this issue in this closed issue that has nothing to do with your issue?

It's a command line tool. Open power shell and run it from there.
